### ISSUE TITLE
Shall type.json and type.jsonb validate real json ([], {}, null, 3, "aaa") other than only objects?

### ISSUE THREAD

**Issue by llonchj** [mibrito/joi-sequelize#3]
According to the JSON specifications, any data type can be specified as a JSON: null, string, numbers, arrays and objects.

In this case, shall [this code](https://github.com/mibrito/joi-sequelize/blob/master/lib/define.js#L87) be changed to:

```
this._joi[key] = joi.any();
```

**Comment by mibrito** [comment]
Sorry for taking so long, you are right.
I've merged your changes and its now also available on npm package now.

Thanks for your contribution :+1:
